apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopcarts
  labels:
    app: shopcarts
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: shopcarts
  template:
    metadata:
      labels:
        app: shopcarts
    spec:
      restartPolicy: Always
      containers:
        - name: shopcarts
          image: bleibowitz13/shopcarts:1.0
          # image: shopcarts
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: database-uri
          resources:
            limits:
              cpu: "0.25"
              memory: "64Mi"
            requests:
              cpu: "0.10"
              memory: "32Mi"
