Feature: Shopcart and Item Management 
    I need a RESTful shopcarts service
    So that I can manage my shopping cart and its items

    Background:
        Given the following shopcarts
            | id | customer_id |
            | 1  | 1           |
            | 2  | 2           |
        And the following items in shopcarts
            | item_id | name   | quantity | price | description       |
            | 1       | Milk   | 2        | 3.50  | Fresh milk carton |
            | 2       | Bread  | 1        | 2.00  | Whole grain loaf  |
            | 3       | Apples | 5        | 1.20  | Red apples pack   |

    Scenario: The server is running
        When I visit the "Home Page"
        Then I should see "Shopcart Demo RESTful Service" in the title
        And I should not see "404 Not Found"
    
    Scenario: List all Shopcarts
        When I visit the "Home Page"
        And I press the "List" button
        # Verifies the data count based on background and backend response
        Then I should see "2" shopcarts in the results

    Scenario: Create a new Shopcart for a Customer
        When I visit the "Home Page"
        When I set the "shopcart_customer_id" to "3"
        When I set the "shopcart id" to "3"
        And I press the "Create shopcart" button
        # This message is generated by the frontend JS upon successful (201) backend response
        Then I should see the message "Success"


    Scenario: Delete a Shopcart
        When I visit the "Home Page"
        And I set the "shopcart_id" to "1"
        And I press the "Delete" button
        # This message is generated by the frontend JS upon successful (204) backend response
        Then I should see the message "Shopcart has been Deleted!"
        When I press the "List" button
        # Verifies the data count after deletion
        Then I should see "2" shopcarts in the results

    Scenario: Add a new item to a shopcart
        When I visit the "Home Page"
        # First create a shopcart
        And I set the "shopcart_customer_id" to "4"
        And I set the "shopcart id" to "4"
        And I press the "Create shopcart" button
        Then I should see the message "Success"
        # Now add an item to the shopcart
        When I set the "item_id" to "101"
        And I set the "name" to "Chocolate" 
        And I set the "quantity" to "3"
        And I set the "price" to "5.99"
        And I set the "description" to "Dark chocolate bar"
        And I press the "create item" button
        Then I should see the message "Success"

    Scenario: Add an item to shopcart and clear the form
        When I visit the "Home Page"
        # First create a shopcart
        And I set the "shopcart_customer_id" to "5"
        And I set the "shopcart id" to "5"
        And I press the "Create shopcart" button
        Then I should see the message "Success"
        # Add an item to the shopcart
        When I set the "item_id" to "102"
        And I set the "name" to "Banana" 
        And I set the "quantity" to "6"
        And I set the "price" to "2.99"
        And I set the "description" to "Fresh yellow bananas"
        And I press the "create item" button
        Then I should see the message "Success"
        # Clear the form and verify fields are empty
        When I press the "clear" button
        Then the "item_id" field should be empty
        And the "name" field should be empty
        And the "quantity" field should be empty
        And the "price" field should be empty
        And the "description" field should be empty

    Scenario: Update an item's name in a shopcart
        When I visit the "Home Page"
        # First create a shopcart
        And I set the "shopcart_customer_id" to "6"
        And I set the "shopcart id" to "6"
        And I press the "Create shopcart" button
        Then I should see the message "Success"
        # Add an item to the shopcart
        When I set the "item_id" to "103"
        And I set the "name" to "Orange Juice" 
        And I set the "quantity" to "2"
        And I set the "price" to "4.99"
        And I set the "description" to "Fresh squeezed orange juice"
        And I press the "create item" button
        Then I should see the message "Success"
        # Update the item's name
        When I change "name" to "Premium Orange Juice"
        And I press the "update" button
        Then I should see the message "Success"
        Then I should see "Premium Orange Juice" in the item results table

